onboarding = false

[keys]
prefix = "ctrl+a"
reload_config = "prefix+r"
workspace_picker = "prefix+a"
goto = "ctrl+h"
new_workspace = "prefix+ctrl+n"
toggle_sidebar = "prefix+p"
close_pane = ""
close_workspace = "prefix+x"
previous_workspace = "prefix+ctrl+k"
next_workspace = "prefix+ctrl+j"
split_vertical = "prefix+backslash"
split_horizontal = ""
zoom = ["prefix+m", "prefix+enter"]
previous_tab = "prefix+ctrl+h"
next_tab = "prefix+ctrl+l"
resize_pane_left = "prefix+shift+h"
resize_pane_down = "prefix+shift+j"
resize_pane_up = "prefix+shift+k"
resize_pane_right = "prefix+shift+l"
new_tab = "prefix+t"
navigate_workspace_down = "j"
navigate_workspace_up = "k"

[[keys.command]]
key = "prefix+d"
type = "popup"
command = "PATH=\"/opt/homebrew/bin:/usr/local/bin:$PATH\" exec lazygit"
description = "lazygit"
width = "100%"
height = "100%"

[[keys.command]]
key = "prefix+n"
type = "popup"
command = "PATH=\"/opt/homebrew/bin:/usr/local/bin:$PATH\" exec nvim"
description = "nvim"
width = "100%"
height = "100%"

[[keys.command]]
key = "prefix+minus"
type = "shell"
command = 'herdr pane split --pane "$HERDR_ACTIVE_PANE_ID" --direction down --ratio 0.75 --focus'
description = "horizontal split"

[ui]
hide_tab_bar_when_single_tab = true
status_indicators = "symbols"
window_title = "{terminal_title}"
pane_gaps = false
pane_outer_borders = false
agent_panel_sort = "priority"

[ui.toast]
delivery = "herdr"

[theme]
name = "tokyo-night"
