font-family = Maple Mono NF
font-size = 13
title = " "
window-padding-x = 10
theme = TokyoNight Moon
macos-titlebar-proxy-icon = hidden
macos-window-shadow = false
font-thicken = true
font-thicken-strength = 0
window-height = 55
window-width = 205
cursor-style = bar
cursor-style-blink = true
unfocused-split-opacity = 1
bell-features = no-audio, no-system, no-title
macos-titlebar-style = transparent
macos-auto-secure-input = true
auto-update-channel = tip

#keybind = ctrl+a>n=new_tab
#keybind = ctrl+a>ctrl+n=new_tab
#keybind = ctrl+a>h=previous_tab
#keybind = ctrl+a>ctrl+h=previous_tab
#keybind = ctrl+a>l=next_tab
#keybind = ctrl+a>ctrl+l=next_tab
#keybind = ctrl+a>\=new_split:right
#keybind = ctrl+a>]=goto_split:next
#keybind = ctrl+a>[=goto_split:previous
